package br.com.justprofit.model.dao.util;

public final class Constants {

	/*
	 * SCRIPTS RELACIONADOS A USUARIO
	 */
	public static final String SCRIPT_SELECT_ALL_USER = "Select * from jpusu";
	
	public static final String SCRIPT_INSERT_USER = "INSERT INTO jpusu (NOME, CNPJ, IE, TELEFONE, "
			+ "EMAIL, CODLOGR, NUMEND, SEGMENTO) VALUES (?,?,?,?,?,?,?,?)";
	
	public static final String SCRIPT_UPDATE_USER = "UPDATE jpusu SET NOME=?, CNPJ=?, IE=?, "
				+ "TELEFONE=?, EMAIL=?, CODLOGR=?, NUMEND=?, SEGMENTO=? WHERE CODUSU=?";
	
	public static final String SCRIPT_DELETE_USER = "DELETE FROM jpusu WHERE CODUSU=?";
	
	public static final String SCRIPT_DELETE_CONTRATO = "DELETE FROM jpcont WHERE CODVEND=?";
	
	public static final String SCRIPT_SELECT_CODUSU = "SELECT CODUSU FROM jpusu WHERE CNPJ = ? AND CODLOGR = ? ";
	
	/*
	 * SCRIPTS RELACIONADOS A VENDEDOR
	 */
	public static final String SCRIPT_SELECT_ALL_VEND = "Select * from jpusu WHERE SEGMENTO = 'V' ORDER BY CODUSU";
	
	public static final String SCRIPT_INSERT_VEND = "INSERT INTO jpven (CODUSU, CODREG) VALUES (?,?)";
	
	public static final String SCRIPT_UPDATE_VEND = "UPDATE jpven SET CODREG=? where CODVEND=? AND CODUSU = ?";
	
	public static final String SCRIPT_BUSCA_IDVEND = "SELECT CODVEND FROM jpven WHERE CODUSU = ? AND CODREG=?";
	
	public static final String SCRIPT_DELETE_VEND = "DELETE FROM jpven WHERE CODUSU=? and CODVEND=?";
	
	public static final String SCRIPT_SELECT_VENDEDOR_BY_ID = "SELECT * FROM jpusu WHERE CODUSU=? AND SEGMENTO = 'V'";
	
	public static final String SCRIPT_SELECT_VENDEDOR_BY_IDVENDEDOR = "SELECT * FROM jpusu WHERE SEGMENTO = 'V' AND CODUSU IN (SELECT CODUSU FROM jpven WHERE codvend = ?)";
	
	public static final String SCRIPT_INSERE_CONTRATO = "INSERT INTO jpcont (CODVEND,CODFORN, DTADM) VALUES (?,?,CURDATE())";
	
	public static final String SCRIPT_SELECT_SALDO_VEND = "SELECT VLRSALDO FROM jpven WHERE CODVEND=?";
	
	public static final String SCRIPT_SELECT_FORNECEDORES_ASSOSIADOS_AO_VENDEDOR = "SELECT CODFORN FROM JPCONT WHERE DTDEM IS NULL AND CODVEND=?";
	
	public static final String SCRIPT_SELECT_NOME_FORNECEDORES_ASSOSIADOS_AO_VENDEDOR = "SELECT UPPER(F.NOME)AS NOME FROM jpcont C INNER JOIN JPUSU F ON F.CODUSU=C.CODFORN WHERE C.DTDEM IS NULL AND C.CODVEND=?";
	
	public static final String SCRIPT_SELECT_TOTAL_FORNECEDORES_ASSOSIADOS_AO_VEND = "SELECT CODVEND FROM JPCONT WHERE DTDEM IS NULL AND CODVEND=?"; 
	
	public static final String SCRIPT_SELECT_VALOR_MENSAL_VENDEDOR = new StringBuilder()
			.append( " SELECT USU.NOME,COALESCE(SUM(ITE.VLRITE),0.0) AS VLRTOTAL " )
			.append( "   FROM JPPED PED	" )
			.append( " INNER JOIN JPITE ITE ON ITE.CODPED=PED.CODPED	" )
			.append( "  INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD	" )
			.append( "   INNER JOIN JPVEN VEN ON VEN.CODVEND=PED.CODVEND	" )
			.append( "   INNER JOIN JPUSU USU ON USU.CODUSU=VEN.CODUSU	" )
			.append( "   WHERE VEN.CODVEND=?	" )
			.append( "   AND PROD.CODFORN=?	" )
			.append( "   AND USU.SEGMENTO='V'" )
			.append( "   AND MONTH(PED.DTPED)=MONTH(CURDATE()) 	" )
			.append( "   AND YEAR(PED.DTPED)=YEAR(CURDATE())  	" )
			.toString();
	
	public static final String SCRIPT_SELECT_RANKING_MENSAL = new StringBuilder()
			.append( " SELECT CONCAT(SUM(ITE.VLRITE),' / ',USU.NOME) AS VLRTOTAL " )
			.append( "   FROM JPPED PED	" )
			.append( " INNER JOIN JPITE ITE ON ITE.CODPED=PED.CODPED	" )
			.append( " INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD " )
			.append( " INNER JOIN JPVEN VEN ON VEN.CODVEND=PED.CODVEND	" )
			.append( " INNER JOIN JPUSU USU ON USU.CODUSU=VEN.CODUSU " )
			.append( " WHERE USU.SEGMENTO='V' " )
			.append( " AND PROD.CODFORN=?" )
			.append( " AND MONTH(PED.DTPED)=MONTH(CURDATE()) " )
			.append( " AND YEAR(PED.DTPED)=YEAR(CURDATE())  " )
			.append( " GROUP BY USU.NOME " )
			.append( " ORDER BY 1 DESC" )
			.append( " LIMIT 5;" )
			.toString();
	
	
	public static final String SCRIPT_SELECT_HISTORICO_POS = new StringBuilder()
			.append( " SELECT COUNT(1) AS PRIMEIRO FROM JPHIST WHERE POSICAO=1 AND CODVEND=?" )
			.append( " UNION ALL" )
			.append( " SELECT COUNT(1) AS PRIMEIRO FROM JPHIST WHERE POSICAO=2 AND CODVEND=?" )
			.toString();

	public static final String SCRIPT_SELECT_RANKING_GRAFICO = new StringBuilder()
			.append( " SELECT " )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -7 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -6 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 6_MESES, " )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -6 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -5 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 5_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -5 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -4 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 4_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -4 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -3 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 3_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -3 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -2 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 2_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -2 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -1 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 1_MESES" )
			.append( " FROM JPPED PED " )
			.append( " INNER JOIN JPITE ITE ON ITE.CODPED=PED.CODPED" )
			.append( " INNER JOIN JPPROD FORN ON FORN.CODPROD=ITE.CODPROD" )
			.append( " WHERE PED.CODVEND=?" )
			.append( " AND FORN.CODFORN=?" )
			.toString();

	
	/*
	 * SCRIPTS RELACIONADOS A FORNCEDOR
	 */
	public static final String SCRIPT_SELECT_FORNECEDOR_BY_ID = "SELECT * FROM jpusu WHERE CODUSU=? AND SEGMENTO = 'F'";
	
	public static final String SCRIPT_SELECT_FORNECEDOR_BY_ID_VENDEDOR = "SELECT * FROM jpusu WHERE codusu IN( SELECT CODFORN FROM jpcont WHERE CODVEND = ?)";
	
	public static final String SCRIPT_SELECT_FORNECEDOR_BY_NAME = "SELECT * FROM JPUSU WHERE NOME like ? AND SEGMENTO = 'F';";
	
	public static final String SCRIPT_SELECT_ALL_FORNECEDOR = "Select * from jpusu WHERE SEGMENTO = 'F' ORDER BY CODUSU";
	
	public static final String SCRIPT_SELECT_VENDEDORES_ASSOSIADOS_AO_FORNECEDOR = "SELECT CODUSU FROM JPUSU WHERE CODUSU IN (SELECT CODUSU FROM JPVEN WHERE CODVEND IN (SELECT CODVEND FROM JPCONT WHERE DTDEM IS NULL AND CODFORN=?))"; 
	
	public static final String SCRIPT_SELECT_TOTAL_VEND_ASSOCIADOS_AO_FORNECEDOR = "SELECT CODVEND FROM JPCONT WHERE DTDEM IS NULL AND CODFORN=?"; 
	
	public static final String SCRIPT_SELECT_TODAS_REGIOES = "SELECT NOMEREG FROM JPREG ORDER BY 1"; 
	
	
	public static final String SCRIPT_SELECT_VALOR_FATURAMENTO_MENSAL_REGIAO = new StringBuilder()
			.append( " SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL " )
			.append( " FROM JPITE ITE " )
			.append( " INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD" )
			.append( " INNER JOIN JPPED PED ON PED.CODPED=ITE.CODPED " )
			.append( " INNER JOIN JPUSU FORN ON FORN.CODUSU=PROD.CODFORN " )
			.append( " INNER JOIN JPUSU CLI ON CLI.CODUSU=PED.CODCLI  " )
			.append( " INNER JOIN jplogr LOGR ON LOGR.CODLOGR=CLI.CODLOGR" )
			.append( " INNER JOIN jpbai BAI ON BAI.CODBAI=LOGR.CODBAI" )
			.append( "  INNER JOIN jpcid CID ON CID.CODCID=BAI.CODCID" )
			.append( " INNER JOIN jpuf UF ON UF.CODUF=CID.CODUF " )
			.append( " INNER JOIN jpreg REG ON REG.CODREG=UF.CODREG " )
			.append( " WHERE REG.CODREG=?" )
			.append( " AND FORN.CODUSU=?" )
			.append( " AND MONTH(PED.DTPED)=MONTH(CURDATE()) " )
			.append( " AND YEAR(PED.DTPED)=YEAR(CURDATE()) " )
			.toString();
	
	public static final String SCRIPT_SELECT_RANKING_VENDEDORES_POR_REGAO = new StringBuilder()
			.append( " SELECT CONCAT(SUM(ITE.VLRITE),' / ',USU.NOME) AS VLRTOTAL " )
			.append( " FROM JPPED PED " )
			.append( " INNER JOIN JPITE ITE ON ITE.CODPED=PED.CODPED" )
			.append( " INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD" )
			.append( " INNER JOIN JPVEN VEN ON VEN.CODVEND=PED.CODVEND" )
			.append( " INNER JOIN JPUSU USU ON USU.CODUSU=VEN.CODUSU" )
			.append( " INNER JOIN JPUSU CLI ON CLI.CODUSU=PED.CODCLI" )
			.append( " INNER JOIN jplogr LOGR ON LOGR.CODLOGR=CLI.CODLOGR" )
			.append( " INNER JOIN jpbai BAI ON BAI.CODBAI=LOGR.CODBAI" )
			.append( " INNER JOIN jpcid CID ON CID.CODCID=BAI.CODCID" )
			.append( " INNER JOIN jpuf UF ON UF.CODUF=CID.CODUF" )
			.append( " INNER JOIN jpreg REG ON REG.CODREG=UF.CODREG" )
			.append( " WHERE REG.CODREG=?" )
			.append( " AND PROD.CODFORN=?" )
			.append( " AND MONTH(PED.DTPED)=MONTH(CURDATE()) " )
			.append( " AND YEAR(PED.DTPED)=YEAR(CURDATE())" )
			.append( " GROUP BY USU.NOME" )
			.append( " ORDER BY 1 DESC" )
			.append( " LIMIT 5" )
			.toString();

	public static final String SCRIPT_SELECT_HISTORICO_PRODOTO_MAIS_VENDIDO = new StringBuilder()
			.append( "SELECT COALESCE(PROD.NOMEPROD,'') AS PRODUTO,COALESCE(COUNT(1),'') AS POSICAO " )
			.append( "FROM JPITE ITE " )
			.append( "INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD " )
			.append( "INNER JOIN JPPED PED ON PED.CODPED=ITE.CODPED " )
			.append( "INNER JOIN JPUSU FORN ON FORN.CODUSU=PROD.CODFORN " )
			.append( "INNER JOIN JPUSU CLI ON CLI.CODUSU=PED.CODCLI " )
			.append( "INNER JOIN jplogr LOGR ON LOGR.CODLOGR=CLI.CODLOGR " )
			.append( "INNER JOIN jpbai BAI ON BAI.CODBAI=LOGR.CODBAI " )
			.append( "INNER JOIN jpcid CID ON CID.CODCID=BAI.CODCID " )
			.append( "INNER JOIN jpuf UF ON UF.CODUF=CID.CODUF " )
			.append( "INNER JOIN jpreg REG ON REG.CODREG=UF.CODREG " )
			.append( "WHERE REG.CODREG=? " )
			.append( "AND FORN.CODUSU=? " )
			.append( "AND MONTH(PED.DTPED)=MONTH(CURDATE()) " )
			.append( "AND YEAR(PED.DTPED)=YEAR(CURDATE())  " )
			.append( "GROUP BY PROD.NOMEPROD " )
			.append( "ORDER BY 2 DESC " )
			.append( "LIMIT 2" )
			.toString();
	
	public static final String SCRIPT_SELECT_RANKING_GRAFICO_FORNECEDOR = new StringBuilder()
			.append( " SELECT" )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -7 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -6 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 6_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -6 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -5 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 5_MESES, " )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -5 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -4 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 4_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -4 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -3 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 3_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -3 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -2 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 2_MESES," )
			.append( " SUM((SELECT COALESCE(SUM(ITE.VLRITE),0) AS VLRTOTAL FROM JPPED P INNER JOIN jpite ITE ON ITE.CODPED=P.CODPED INNER JOIN JPPROD PROD ON PROD.CODPROD=ITE.CODPROD WHERE P.DTPED BETWEEN DATE_ADD(CURDATE(), INTERVAL -2 MONTH)  AND DATE_ADD(CURDATE(), INTERVAL -1 MONTH) AND P.CODVEND=PED.CODVEND AND PROD.CODFORN=FORN.CODFORN)) AS 1_MESES " )
			.append( "	FROM JPPED PED  " )
			.append( " INNER JOIN JPITE ITE ON ITE.CODPED=PED.CODPED " )
			.append( " INNER JOIN JPPROD FORN ON FORN.CODPROD=ITE.CODPROD " )
			.append( " INNER JOIN JPUSU CLI ON CLI.CODUSU=PED.CODCLI " )
			.append( " INNER JOIN jplogr LOGR ON LOGR.CODLOGR=CLI.CODLOGR " )
			.append( " INNER JOIN jpbai BAI ON BAI.CODBAI=LOGR.CODBAI " )
			.append( " INNER JOIN jpcid CID ON CID.CODCID=BAI.CODCID " )
			.append( " INNER JOIN jpuf UF ON UF.CODUF=CID.CODUF " )
			.append( " INNER JOIN jpreg REG ON REG.CODREG=UF.CODREG " )
			.append( " WHERE REG.CODREG=? " )
			.append( " AND FORN.CODFORN=? " )
			.append( " AND MONTH(PED.DTPED)=MONTH(CURDATE())  " )
			.append( " AND YEAR(PED.DTPED)=YEAR(CURDATE())  " )
			.toString();
	
	/*
	 * busca vendedor por id fornecedor
		SELECT * FROM jpusu WHERE codusu IN(SELECT codusu FROM jpven WHERE codvend IN (SELECT codvend FROM jpcont WHERE CODFORN = ?));
	 */
	
	/*
	 * Insert de endereço
	 */
	public static final String SCRIPT_INSERT_REG = "INSERT INTO jpreg (NOMEREG) VALUES (?)";
		
	public static final String SCRIPT_INSERT_UF = "INSERT INTO jpuf (UF,CODREG) VALUES (?,(SELECT CODREG FROM jpreg WHERE NOMEREG = ? LIMIT 1))";
	
	public static final String SCRIPT_INSERT_CID = "INSERT INTO jpcid (NOMECID,CODUF) VALUES (?, (SELECT CODUF FROM JPUF WHERE UF = ?))";
	
	public static final String SCRIPT_INSERT_BAI = "INSERT INTO jpbai (NOMEBAI,CODCID) VALUES (?, (SELECT CODCID FROM JPCID WHERE NOMECID = ?))";
	
	public static final String SCRIPT_INSERT_LOGR = "INSERT INTO jplogr (NOMELOGR,CODBAI,CEP) VALUES (?, (SELECT CODBAI FROM jpbai WHERE NOMEBAI = ? ), ?)";
	
	public static final String SCRIPT_BUSCA_CODLOGR_USU = "SELECT CODLOGR FROM jplogr WHERE CEP = ? AND NOMELOGR = ? AND CODBAI = (SELECT CODBAI FROM jpbai WHERE NOMEBAI = ? )";
	
	public static final String SCRIPT_BUSCA_ENDERECO_BY_CEP = "SELECT * FROM JPLOGR WHERE CEP=? LIMIT 1";
	
	
	/*
	 * SCRIPTS RELACIONADOS A CLIENTE
	 */
	
	public static final String SCRIPT_SELECT_ALL_CLIENTE = "SELECT * FROM jpusu WHERE SEGMENTO = 'C' ORDER BY CODUSU";
	
	public static final String SCRIPT_SELECT_CLIENTE_BY_ID = "SELECT * FROM jpusu WHERE CODUSU=? AND SEGMENTO = 'C'";
	
	public static final String SCRIPT_SELECT_CLIENTE_BY_ID_VENDEDOR = new StringBuilder()
			.append( "SELECT USU.CODUSU,USU.NOME,USU.CNPJ,USU.IE,USU.TELEFONE,USU.EMAIL,USU.SEGMENTO " )
			.append( " FROM jpusu USU" )
			.append( " WHERE CODUSU IN (SELECT DISTINCT CODCLI FROM JPPED WHERE CODVEND=?)" )
			.toString();
	
	/*
	 * SCRIPT RELACIONADOS A ENDERECO
	 */
	public static final String SCRIPT_SELECT_LOG_AND_NUM_USER = "SELECT CODLOGR,NUMEND FROM jpusu WHERE CODUSU=?";
	
	public static final String SCRIPT_SELECT_LOGADOURO = "SELECT * FROM jplogr WHERE CODLOGR=?"; 
	
	public static final String SCRIPT_SELECT_CIDADE = "SELECT * FROM jpcid WHERE CODCID=?"; 
	
	public static final String SCRIPT_SELECT_BAIRRO = "SELECT * FROM jpbai WHERE CODBAI=?"; 
	
	public static final String SCRIPT_SELECT_ESTADO = "SELECT * FROM jpuf WHERE CODUF=?";
	
	public static final String SCRIPT_SELECT_REG = "SELECT * FROM jpreg WHERE CODREG=?";
	
	public static final String SCRIPT_SELECT_CODREG_POR_NOME = "SELECT CODREG FROM jpreg WHERE NOMEREG=?";
	
	
	/*
	 * SCRIPT RELACIONADOS A PRODUTO
	 */
	
	public static final String SCRIPT_SELECT_PRODUTO_POR_ID = "SELECT * FROM JPPROD WHERE CODPROD = ?";
	
	//public static final String SCRIPT_SELECT_ALL_PRODUTO= "Select * from JPPROD ORDER BY CODPROD";
	public static final String SCRIPT_SELECT_ALL_PRODUTO = new StringBuilder()
			.append( " SELECT PROD.CODPROD,PROD.NOMEPROD,FORN.NOME,PROD.VLRTOT,PROD.DESCMAX " )
			.append( " FROM JPPROD PROD " )
			.append( " INNER JOIN JPUSU FORN ON FORN.CODUSU=PROD.CODFORN" )
			.append( " WHERE FORN.CODUSU IN (SELECT DISTINCT CODFORN AS CODUSU FROM jpcont WHERE CODVEND=? AND DTDEM IS NULL)" )
			.append( " ORDER BY 3,1" )
			.toString();

	/*
	 * SCRIPT RELACIONADOS A PEDIDO
	 */
	public static final String SCRIPT_SELECT_PEDIDO_POR_ID = "SELECT * FROM JPPED WHERE CODPED = ?";
	
	public static final String SCRIPT_SELECT_ALL_PEDIDO = "Select * from JPPED ORDER BY CODPED";
}
